import =[
  "~/.config/alacritty/themes/themes/gruvbox_dark.toml"
]
[env]
TERM = "xterm-256color"

[window]

decorations = "Buttonless"

opacity = 0.7
blur = true

startup_mode = "SimpleFullscreen"

option_as_alt = "Both"

[font]
normal.family = "Hack Nerd Font Mono"

size = 18
